server:
  port: 8080
spring:
  datasource:
    username: achat
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/achat
  jpa:
    show-sql: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
achat:
   websocket:
      allow-origin: http://localhost:3000
   chat-file-folder: "F:\\aChat\\chat-file\\"
      