version: '3.7'
services:
    db-mysql:
      image: mysql:8.0.19
      environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_USER: achat
        MYSQL_PASSWORD: password
      ports:
          - 3306:3306
